package Tokens;

public enum TokenType {

	INICIO_PROGRAMA, FIN_PROGRAMA, OPERADOR_ARITMETICO, OPERADOR_RELACIONAL, IDENTIFICADOR,
	LEER, ESCRIBIR, SI, ENTONCES, MIENTRAS, INICIO, FIN, FLOTANTE, ASIGNACION, PALABRA,
	NUMERO, STRING, GUION_BAJO, DOS_PUNTOS,
}
