package Tokens;

public enum TokenType {

	INICIO_PROGRAMA, FIN_PROGRAMA, OPERADOR_MATEMATICO, OPERADOR_RELACIONAL, IDENTIFICADOR,
	LEER, ESCRIBIR, SI, ENTONCES, MIENTRAS, INICIO, FLOTANTE, ASIGNACION
}
